name: Make on multiple platforms

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        c_compiler: [gcc]
        include:
          - os: windows-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: gcc

    steps:
    - uses: actions/checkout@v4
    
    - name: Install ALSA lib on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev

    - name: Make build directory
      run: make

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./build
